project:
  type: website

website:
  title: "Aster Hu's Blog | Asteroid"
  description: "My blog about learning, thinking, knitting, programming"
  site-url: "https://www.asterhu.com"
  google-analytics: "G-1E2YF2TSNE"
  favicon: about/favicon.ico
  page-footer:
    left: "This blog is built with ❤️ and [Quarto](https://quarto.org/). Copyright © 2020-2025 Aster Hu. All rights reserved."
    right:
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/aster-hu/
      - icon: envelope
        href: mailto:hello@asterhu.com
  navbar:
    title: "Asteroid"
    background: "#83b7bb"
    foreground: "#FFFFFF"
    pinned: true
    logo: about/favicon.ico
    right:
      - text: "learning · thinking · knitting · programming"
    left:
      - text: About
        href: about/index.qmd
      - text: Post
        href: post/
      - text: Thoughts
        href: thoughts/
      - text: Notebook
        href: https://notes.asterhu.com
      - text: Knitting
        href: https://purringyarn.pages.dev
      - text: "RSS Subscribe"
        icon: rss
        menu:
          - text: RSS - Post
            url: /post/index.xml
          - text: RSS - Thoughts
            url: /thoughts/index.xml
    backgroundcolor: "#faf8f8"
    tools:
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/aster-hu/Asteroid_Blog
          - text: Report a Bug
            url: https://github.com/aster-hu/Asteroid_Blog/issues

format:
  html:
    smooth-scroll: true
    theme: [litera, styles.scss]
    link-external-icon: true
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
    toc: true
    toc-depth: 3
    toc-title: "Contents"
    toc-location: left
    code-link: false
    anchor-sections: true
    code-tools: false
    code-fold: false
    highlight-style: ayu
    reference-location: document
    fig-cap-location: margin
    grid:
      sidebar-width: 275px
      body-width: 800px
      margin-width: 250px

execute:
  warning: false
  message: false
  freeze: auto
