project:
  type: website

website:
  title: "Aster Hu's Blog | Asteroid"
  description: "learning · programming · arts · random thoughts"
  site-url: "https://www.asterhu.com"
  google-analytics: "G-1E2YF2TSNE"
  favicon: about/favicon.ico
  page-footer:
    left: "This blog is built with ❤️ and [Quarto](https://quarto.org/). License: [CC BY-NC-SA 4.0](http://creativecommons.org/licenses/by-nc-sa/4.0/)."
    right:
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/aster-hu/
      - icon: envelope
        href: mailto:hello@asterhu.com
  navbar:
    title: "Asteroid"
    background: "#83b7bb"
    foreground: "#FFFFFF"
    pinned: true
    logo: about/favicon.ico
    left: 
      - text: "learning · programming · arts · random thoughts"
    right:
      - text: About 
        href: about/index.qmd
      - text: Post
        href: post/
      - text: Notes
        href: https://notes.asterhu.com
      - text: Purling Thoughts
        href: https://thoughts.asterhu.com
      - text: Resources
        href: links/index.qmd
      - icon: rss
        text: "RSS Subscribe"
        href: index.xml
    backgroundcolor: "#faf8f8"
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/aster-hu/Asteroid_Blog
          - text: Report a Bug
            url:  https://github.com/aster-hu/Asteroid_Blog/issues

format:
  html:
    smooth-scroll: true
    theme: [litera, styles.scss]
    link-external-icon: true
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
    toc: true
    toc-depth: 3
    toc-title: "Contents"
    toc-location: left
    code-link: false
    anchor-sections: true
    code-tools: false
    code-fold: false
    highlight-style: ayu
    reference-location: document
    fig-cap-location: margin
    grid:
      sidebar-width: 275px
      body-width: 800px
      margin-width: 250px

execute:
  warning: false
  message: false
  freeze: auto
